define:
    qfed_base_dir: &qfed_base_dir /discover/nobackup/projects/gmao/share/gmao_ops/fvInput/ExtData/chemistry/QFED/v3.2-nrt/sfc/0.1/
    modis_base_dir: &modis_base_dir /discover/nobackup/dao_ops/intermediate/flk/modis.061/ 

qfed:
    scaling:
        #file: /dev/null        
        file: /discover/nobackup/projects/gmao/geos_aerosols/acollow/QFED/qfed3_regional_scaling_masks.nc4
        species: ['co2', 'oc', 'so2', 'nh3', 'bc', 'co', 'acet', 'ald2', 'alk4', 'c2h6', 'c3h8', 'ch2o', 'mek', 'no', 'c3h6', 'pm25', 'tpm', 'ch4']
    output:
        grid:
            resolution: '0.1x0.1'  # choose from ('c', 'd', 'e', 'f', '0.1x0.1')
        emissions:
            species: ['co2', 'oc', 'so2', 'nh3', 'bc', 'co', 'acet', 'ald2', 'alk4', 'c2h6', 'c3h8', 'ch2o', 'mek', 'no', 'c3h6', 'pm25', 'tpm', 'ch4']
            file:
             - *qfed_base_dir
             - "QFED"
             - "Y{0:%Y}/M{0:%m}"
             - "qfed_emis_x3600y1800_{{species}}.{{version}}.{0:%Y%m%d}.nc4"
            doi: "10.5067/OA7JO5RLJCO2"
        frp:
            file:
             - *qfed_base_dir
             - "FRP"
             - "Y{0:%Y}/M{0:%m}"
             - "qfed_frp_{{sat}}.{{version}}.{0:%Y%m%d}.nc4"
        frp_fcs:
            file: 
             - *qfed_base_dir
             - "FRP_FCS"
             - "Y{0:%Y}/M{0:%m}"
             - "qfed_frp-fcst_{{sat}}.{{version}}.{0:%Y%m%d}.nc4"
    with:
        mod: # MODIS TERRA
            geolocation:
                file: /discover/nobackup/projects/gmao/input/dao_ops/ops/flk/modis/061//MOD03/{0:%Y}/{0:%j}/MOD03.A{0:%Y%j}.{0:%H%M}.061.*.hdf
            fires:
                file: /discover/nobackup/projects/gmao/input/dao_ops/ops/flk/modis/061/MOD14/{0:%Y}/{0:%j}/MOD14.A{0:%Y%j}.{0:%H%M}.061.*.hdf
        myd: # MODIS AQUA
            geolocation:
                file: /discover/nobackup/projects/gmao/input/dao_ops/ops/flk/modis/061/MYD03/{0:%Y}/{0:%j}/MYD03.A{0:%Y%j}.{0:%H%M}.061.*.hdf
            fires: 
                file: /discover/nobackup/projects/gmao/input/dao_ops/ops/flk/modis/061/MYD14/{0:%Y}/{0:%j}/MYD14.A{0:%Y%j}.{0:%H%M}.*.hdf
        vnp:  # VIIRS S-NPP
            geolocation:
                file: /css/viirs/data/Level1/VNP03IMG_NRT.trimmed/{0:%Y}/{0:%j}/VNP03IMG.A{0:%Y%j}.{0:%H%M}.0[02][21].*.nc
            fires:
                file: /css/viirs/data/Level2/VNP14IMG_NRT/{0:%Y}/{0:%j}/VNP14IMG.A{0:%Y%j}.{0:%H%M}.002.*.nc
        vj1: # VIIRS JPSS1
            geolocation:
                file: /css/viirs/data/Level1/VJ103IMG_NRT.trimmed/{0:%Y}/{0:%j}/VJ103IMG.A{0:%Y%j}.{0:%H%M}.0[02][21].*.nc
            fires:
                file: /css/viirs/data/Level2/VJ114IMG_NRT/{0:%Y}/{0:%j}/VJ114IMG.A{0:%Y%j}.{0:%H%M}.002.*.nc
        vj2: # VIIRS JPSS2
            geolocation:
                file: /css/viirs/data/Level1/VJ203IMG_NRT.trimmed/{0:%Y}/{0:%j}/VJ203IMG.A{0:%Y%j}.{0:%H%M}.0[02][21].*.nc
            fires:
                file: /css/viirs/data/Level2/VJ214IMG_NRT/{0:%Y}/{0:%j}/VJ214IMG.A{0:%Y%j}.{0:%H%M}.002.*.nc

        igbp: /discover/nobackup/projects/gmao/share/gmao_ops/qfed/Emissions/Vegetation/GL_IGBP_INPE/
        watermask: /discover/nobackup/projects/gmao/geos_aerosols/shared/emissions/watermask/watermask-700m.no_coast.nc4
